#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Execute one guarded Scene3 6D gripper-alignment step.

The plan is generated by ``scene3_gripper_6d_align_plan.py``.  This executor
interpolates the complete 14-joint command reference, checks the physical
finger geometry after motion, and rolls back if the three-axis orientation
does not improve while the physical TCP remains nearly fixed.  The base and
claw are never controlled.
"""

from __future__ import print_function

import argparse
import math
import statistics
import time

import numpy as np

from scene3_6d_pose_dry_run import (
    REFERENCE_PARAM,
    extract_arm_joints,
    position_error,
    quaternion_error_degrees,
)
from scene3_gripper_6d_align_plan import (
    GRIPPER_BASE_FRAME,
    LEFT_FINGER_FRAME,
    PLAN_PARAM,
    RIGHT_FINGER_FRAME,
    TARGET_ODOM_PARAM,
    gripper_geometry,
)


CONFIRMATION = "SCENE3_GRIPPER_6D_ALIGN_5DEG"
ARM_NAMES = ["arm_joint_{}".format(index) for index in range(1, 15)]


def quintic(progress):
    value = max(0.0, min(1.0, float(progress)))
    return 10.0 * value ** 3 - 15.0 * value ** 4 + 6.0 * value ** 5


def maximum_abs(values):
    values = list(values)
    return max(abs(float(value)) for value in values) if values else 0.0


def rotation_error_degrees(target, actual):
    relative = np.asarray(target, dtype=float).dot(
        np.asarray(actual, dtype=float).T
    )
    cosine = float(np.clip((np.trace(relative) - 1.0) * 0.5, -1.0, 1.0))
    return math.degrees(math.acos(cosine))


def post_motion_checks(
        before_error,
        after_error,
        tcp_shift,
        final_position_error,
        final_orientation_error,
        left_drift,
        right_tracking_error,
        tray_standoff,
        minimum_error_reduction=1.5,
        maximum_tcp_shift=0.015):
    reduction = float(before_error) - float(after_error)
    checks = {
        "physical_orientation_improved": (
            reduction >= float(minimum_error_reduction)
        ),
        "tcp_held": float(tcp_shift) <= float(maximum_tcp_shift),
        "eef_position_bounded": float(final_position_error) <= 0.010,
        "eef_orientation_bounded": float(final_orientation_error) <= 4.0,
        "left_arm_bounded": float(left_drift) <= 1.5,
        "right_tracking_bounded": float(right_tracking_error) <= 2.0,
        "tray_still_ahead": float(tray_standoff) >= 0.055,
    }
    return checks, reduction


def build_parser():
    parser = argparse.ArgumentParser(
        description="Execute one guarded TCP-held 6D gripper alignment step"
    )
    parser.add_argument("--execute", action="store_true")
    parser.add_argument("--confirmation", default="")
    parser.add_argument("--motion-seconds", type=float, default=4.0)
    parser.add_argument("--rollback-seconds", type=float, default=4.0)
    parser.add_argument("--settle-seconds", type=float, default=1.5)
    parser.add_argument("--hz", type=float, default=50.0)
    parser.add_argument("--maximum-baseline-error-deg", type=float, default=1.0)
    parser.add_argument("--maximum-reference-error-deg", type=float, default=0.10)
    parser.add_argument("--maximum-joint-step-deg", type=float, default=8.0)
    parser.add_argument("--maximum-planned-angle-deg", type=float, default=5.5)
    parser.add_argument("--maximum-plan-tcp-error", type=float, default=0.012)
    parser.add_argument("--maximum-target-change", type=float, default=0.020)
    parser.add_argument("--minimum-error-reduction", type=float, default=1.5)
    parser.add_argument("--maximum-tcp-shift", type=float, default=0.015)
    parser.add_argument("--timeout", type=float, default=8.0)
    return parser


def run_ros(args):
    import rospy
    import tf2_ros
    from kuavo_msgs.msg import sensorsData
    from geometry_msgs.msg import PointStamped
    from kuavo_msgs.srv import (
        changeArmCtrlMode,
        changeArmCtrlModeRequest,
        fkSrv,
    )
    from sensor_msgs.msg import JointState

    if not args.execute or args.confirmation != CONFIRMATION:
        raise RuntimeError(
            "execution blocked; pass --execute --confirmation {}".format(
                CONFIRMATION
            )
        )

    rospy.init_node("scene3_gripper_6d_align_execute", anonymous=True)
    if not rospy.has_param(PLAN_PARAM):
        raise RuntimeError("6D gripper alignment plan is unavailable")
    plan = rospy.get_param(PLAN_PARAM)
    required = (
        "source_arm_rad",
        "target_arm_rad",
        "source_reference_deg",
        "target_reference_deg",
        "target_eef_position",
        "target_eef_quaternion_xyzw",
        "physical_tcp_before",
        "desired_physical_rotation",
        "physical_error_before_deg",
        "planned_orientation_step_deg",
        "target_tray_base_xyz",
        "target_tray_odom_xyz",
        "tcp_extension_m",
    )
    missing = [key for key in required if key not in plan]
    if missing:
        raise RuntimeError("alignment plan is missing fields: {}".format(missing))

    source_arm = [float(value) for value in plan["source_arm_rad"]]
    target_arm = [float(value) for value in plan["target_arm_rad"]]
    source_reference = [
        float(value) for value in plan["source_reference_deg"]
    ]
    target_reference = [
        float(value) for value in plan["target_reference_deg"]
    ]
    target_eef_position = [
        float(value) for value in plan["target_eef_position"]
    ]
    target_eef_quaternion = [
        float(value) for value in plan["target_eef_quaternion_xyzw"]
    ]
    saved_tcp = np.asarray(plan["physical_tcp_before"], dtype=float)
    desired_physical_rotation = np.asarray(
        plan["desired_physical_rotation"], dtype=float
    ).reshape(3, 3)
    saved_tray = np.asarray(plan["target_tray_base_xyz"], dtype=float)
    saved_tray_odom = np.asarray(
        plan["target_tray_odom_xyz"], dtype=float
    )
    planned_angle = float(plan["planned_orientation_step_deg"])
    tcp_extension = float(plan["tcp_extension_m"])
    if not all(len(values) == expected for values, expected in (
        (source_arm, 14),
        (target_arm, 14),
        (source_reference, 14),
        (target_reference, 14),
        (target_eef_position, 3),
        (target_eef_quaternion, 4),
    )):
        raise RuntimeError("alignment plan has invalid array lengths")

    current_reference = rospy.get_param(REFERENCE_PARAM, None)
    if not isinstance(current_reference, (list, tuple)) or len(current_reference) != 14:
        raise RuntimeError("arm command reference is unavailable")
    current_reference = [float(value) for value in current_reference]

    tf_buffer = tf2_ros.Buffer(cache_time=rospy.Duration(10.0))
    listener = tf2_ros.TransformListener(tf_buffer)
    rospy.sleep(1.5)

    def frame_xyz(frame_name):
        transform = tf_buffer.lookup_transform(
            "base_link", frame_name, rospy.Time(0), rospy.Duration(3.0)
        )
        translation = transform.transform.translation
        return np.array(
            [translation.x, translation.y, translation.z], dtype=float
        )

    def point_in_base(xyz, source_frame):
        point = PointStamped()
        point.header.frame_id = str(source_frame)
        point.header.stamp = rospy.Time(0)
        point.point.x = float(xyz[0])
        point.point.y = float(xyz[1])
        point.point.z = float(xyz[2])
        transformed = tf_buffer.transform(
            point, "base_link", rospy.Duration(3.0)
        )
        return np.array([
            transformed.point.x,
            transformed.point.y,
            transformed.point.z,
        ], dtype=float)

    def physical_geometry():
        return gripper_geometry(
            frame_xyz(GRIPPER_BASE_FRAME),
            frame_xyz(LEFT_FINGER_FRAME),
            frame_xyz(RIGHT_FINGER_FRAME),
            tcp_extension_m=tcp_extension,
        )

    rospy.wait_for_service("/ik/fk_srv", timeout=float(args.timeout))
    fk_proxy = rospy.ServiceProxy("/ik/fk_srv", fkSrv)

    def call_fk(arm):
        response = fk_proxy([float(value) for value in arm])
        if not getattr(response, "success", False):
            raise RuntimeError("/ik/fk_srv failed")
        return response.hand_poses

    def sample_arm(count=5):
        samples = []
        for _ in range(int(count)):
            message = rospy.wait_for_message(
                "/sensors_data_raw", sensorsData, timeout=float(args.timeout)
            )
            arm, _ = extract_arm_joints(message)
            samples.append([float(value) for value in arm])
            rospy.sleep(0.06)
        return [
            statistics.median(sample[index] for sample in samples)
            for index in range(14)
        ]

    arm_publisher = rospy.Publisher(
        "/kuavo_arm_traj", JointState, queue_size=10
    )
    deadline = time.time() + float(args.timeout)
    while arm_publisher.get_num_connections() == 0:
        if time.time() >= deadline:
            raise RuntimeError("/kuavo_arm_traj has no subscriber")
        rospy.sleep(0.05)

    def publish_once(values):
        message = JointState()
        message.header.stamp = rospy.Time.now()
        message.name = ARM_NAMES
        message.position = [float(value) for value in values]
        arm_publisher.publish(message)

    def move_reference(start, target, duration):
        steps = max(1, int(float(duration) * float(args.hz)))
        rate = rospy.Rate(float(args.hz))
        latest = list(start)
        for step in range(steps + 1):
            alpha = quintic(float(step) / float(steps))
            latest = [
                float(start[index])
                + (float(target[index]) - float(start[index])) * alpha
                for index in range(14)
            ]
            publish_once(latest)
            if step % max(1, int(args.hz / 10.0)) == 0:
                rospy.set_param(REFERENCE_PARAM, latest)
            rate.sleep()
        rospy.set_param(REFERENCE_PARAM, [float(value) for value in target])

    def hold_reference(values, duration):
        rate = rospy.Rate(float(args.hz))
        deadline_local = time.time() + float(duration)
        while not rospy.is_shutdown() and time.time() < deadline_local:
            publish_once(values)
            rate.sleep()

    current_arm = sample_arm()
    before_geometry = physical_geometry()
    current_tray_odom = np.asarray(
        rospy.get_param(TARGET_ODOM_PARAM), dtype=float
    )
    current_tray = point_in_base(current_tray_odom, "odom")
    baseline_error = maximum_abs([
        math.degrees(current_arm[index] - source_arm[index])
        for index in range(14)
    ])
    reference_error = maximum_abs([
        current_reference[index] - source_reference[index]
        for index in range(14)
    ])
    joint_step = [
        target_reference[index] - source_reference[index]
        for index in range(14)
    ]
    tcp_plan_error = float(np.linalg.norm(before_geometry["tcp"] - saved_tcp))
    target_change = float(np.linalg.norm(
        current_tray_odom - saved_tray_odom
    ))
    before_error = rotation_error_degrees(
        desired_physical_rotation, before_geometry["rotation"]
    )
    pre_checks = {
        "baseline_fresh": baseline_error <= args.maximum_baseline_error_deg,
        "reference_fresh": reference_error <= args.maximum_reference_error_deg,
        "left_command_held": maximum_abs(joint_step[:7]) <= 1e-6,
        "right_joint_step_bounded": (
            maximum_abs(joint_step[7:14]) <= args.maximum_joint_step_deg
        ),
        "orientation_step_bounded": (
            0.5 <= planned_angle <= args.maximum_planned_angle_deg
        ),
        "physical_tcp_fresh": tcp_plan_error <= args.maximum_plan_tcp_error,
        "tray_target_fresh": target_change <= args.maximum_target_change,
    }

    print("Physical TCP before: {}".format(
        np.round(before_geometry["tcp"], 4).tolist()
    ))
    print("Physical forward before: {}".format(
        np.round(before_geometry["forward"], 4).tolist()
    ))
    print("Physical gap axis before: {}".format(
        np.round(before_geometry["gap"], 4).tolist()
    ))
    print("Physical up axis before: {}".format(
        np.round(before_geometry["up"], 4).tolist()
    ))
    print("Full physical orientation error before: {:.2f}deg".format(
        before_error
    ))
    print("Planned orientation step: {:.2f}deg".format(planned_angle))
    print("Right-arm command step: {}deg".format(
        [round(value, 3) for value in joint_step[7:14]]
    ))
    print("Plan TCP freshness error: {:.1f}mm".format(
        tcp_plan_error * 1000.0
    ))
    print("Pre-execution checks: {}".format(pre_checks))
    if not all(pre_checks.values()):
        print("GRIPPER_6D_ALIGN_EXECUTION_BLOCKED: stale or unsafe plan")
        print("No control command was sent")
        return 2

    mode_ok = False
    for service_name in (
        "/arm_traj_change_mode",
        "/humanoid_change_arm_ctrl_mode",
    ):
        try:
            rospy.wait_for_service(service_name, timeout=2.0)
            mode_proxy = rospy.ServiceProxy(service_name, changeArmCtrlMode)
            request = changeArmCtrlModeRequest()
            request.control_mode = 2
            response = mode_proxy(request)
            if getattr(response, "result", False):
                mode_ok = True
                print("Arm mode 2 enabled via {}".format(service_name))
                break
        except Exception:
            pass
    if not mode_ok:
        print("GRIPPER_6D_ALIGN_EXECUTION_BLOCKED: cannot enable arm mode 2")
        return 2

    moved = False
    try:
        print("Executing one smooth 5deg 6D gripper turn; TCP stays fixed")
        print("Base and claw remain untouched")
        moved = True
        move_reference(source_reference, target_reference, args.motion_seconds)
        hold_reference(target_reference, args.settle_seconds)

        after_arm = sample_arm()
        after_poses = call_fk(after_arm)
        after_eef_position = [
            float(value) for value in after_poses.right_pose.pos_xyz
        ]
        after_eef_quaternion = [
            float(value) for value in after_poses.right_pose.quat_xyzw
        ]
        after_geometry = physical_geometry()
        after_error = rotation_error_degrees(
            desired_physical_rotation, after_geometry["rotation"]
        )
        tcp_shift = float(np.linalg.norm(
            after_geometry["tcp"] - before_geometry["tcp"]
        ))
        final_position_error = position_error(
            target_eef_position, after_eef_position
        )
        final_orientation_error = quaternion_error_degrees(
            target_eef_quaternion, after_eef_quaternion
        )
        left_drift = maximum_abs([
            math.degrees(after_arm[index] - current_arm[index])
            for index in range(7)
        ])
        right_tracking_error = maximum_abs([
            math.degrees(after_arm[index] - target_arm[index])
            for index in range(7, 14)
        ])
        tray_vector = current_tray - after_geometry["tcp"]
        tray_standoff = float(np.dot(
            tray_vector, desired_physical_rotation[:, 0]
        ))
        post_checks, reduction = post_motion_checks(
            before_error,
            after_error,
            tcp_shift,
            final_position_error,
            final_orientation_error,
            left_drift,
            right_tracking_error,
            tray_standoff,
            minimum_error_reduction=args.minimum_error_reduction,
            maximum_tcp_shift=args.maximum_tcp_shift,
        )

        print("Physical TCP after: {}".format(
            np.round(after_geometry["tcp"], 4).tolist()
        ))
        print("Physical forward after: {}".format(
            np.round(after_geometry["forward"], 4).tolist()
        ))
        print("Physical gap axis after: {}".format(
            np.round(after_geometry["gap"], 4).tolist()
        ))
        print("Physical up axis after: {}".format(
            np.round(after_geometry["up"], 4).tolist()
        ))
        print("Physical orientation error: {:.2f}deg -> {:.2f}deg".format(
            before_error, after_error
        ))
        print("Actual orientation improvement: {:.2f}deg".format(reduction))
        print("Physical TCP shift: {:.1f}mm".format(tcp_shift * 1000.0))
        print("Final EEF residual: position={:.4f}m orientation={:.2f}deg".format(
            final_position_error, final_orientation_error
        ))
        print("Left-arm drift: {:.3f}deg".format(left_drift))
        print("Right-arm tracking error: {:.3f}deg".format(
            right_tracking_error
        ))
        print("Tray forward standoff: {:.1f}mm".format(
            tray_standoff * 1000.0
        ))
        print("Post-execution checks: {}".format(post_checks))
        if not all(post_checks.values()):
            raise RuntimeError("post-motion physical 6D gate failed")

        if rospy.has_param(PLAN_PARAM):
            rospy.delete_param(PLAN_PARAM)
        print("GRIPPER_6D_ALIGN_5DEG_OK")
        print("Command reference updated; plan one more step if needed")
        print("Base and claw were not controlled")
        return 0
    except Exception as exc:
        print("ROLLBACK: {}".format(exc))
        if moved:
            start = rospy.get_param(REFERENCE_PARAM, target_reference)
            move_reference(start, source_reference, args.rollback_seconds)
            hold_reference(source_reference, args.settle_seconds)
            rospy.set_param(REFERENCE_PARAM, source_reference)
        print("GRIPPER_6D_ALIGN_EXECUTION_BLOCKED: rolled back")
        print("Claw remains open")
        return 2


def main(argv=None):
    return run_ros(build_parser().parse_args(argv))


if __name__ == "__main__":
    raise SystemExit(main())

